mastermind_api:
    resource: "@MastermindApiBundle/Resources/config/routing.yml"
    prefix:   /api

mastermind_core:
    resource: "@MastermindCoreBundle/Resources/config/routing.yml"
    prefix:   /

games:
    type:     rest
    resource: Mastermind\ApiBundle\Controller\GameController
