mastermind_api:
    resource: "@MastermindApiBundle/Resources/config/routing.yml"
    prefix:   /api

games:
    type:     rest
    resource: Mastermind\ApiBundle\Controller\GameController

multiplayer:
    type:     rest
    resource: Mastermind\ApiBundle\Controller\MultiplayerController
