# Learn more about services, parameters and containers at
# http://symfony.com/doc/current/book/service_container.html
parameters:
#    parameter_name: value

services:
    mastermind.game_builder:
        class: Mastermind\CoreBundle\Builder\GameBuilder
        arguments: ["@doctrine_mongodb.odm.default_document_manager"]
    mastermind.multiplayer_builder:
        class: Mastermind\CoreBundle\Builder\MultiplayerBuilder
        arguments: ["@doctrine_mongodb.odm.default_document_manager"]
